import type { ExpertiseDomain } from '../types/expertise';

export const EXPERTISE_DOMAINS: ExpertiseDomain[] = [
  {
    id: 'applied-ai',
    title: 'Applied AI & Machine Learning',
    subtitle: 'Agentic Workflows, Semantic Search & Neural Networks',
    iconName: 'BrainCircuit',
    flowSequence: 'LLMs → LangChain/LangGraph → RAG → Vector Databases → Deep Learning',
    description:
      'Designing intelligent systems combining modern large language models with retrieval pipelines and foundational neural network architectures.',
    nodes: [
      {
        id: 'llms',
        name: 'Large Language Models (LLMs)',
        maturity: 'Advanced',
        role: 'Leveraging foundational models for complex reasoning, data extraction, and natural language understanding.',
        connectedNodes: ['langchain', 'langgraph'],
        projects: ['PAIN AWAY', 'Mem-Rooted', 'TranslateIQ', 'Learnify'],
      },
      {
        id: 'langchain',
        name: 'LangChain',
        maturity: 'Advanced',
        role: 'Building robust LLM application chains, integrating external tools, and managing conversational memory context.',
        connectedNodes: ['langgraph', 'rag'],
        projects: ['Mem-Rooted', 'Autonomous CI/CD Healing Agent'],
      },
      {
        id: 'langgraph',
        name: 'LangGraph Stateful Workflows',
        maturity: 'Working Knowledge',
        role: 'Structuring cyclical agent behaviors and stateful workflows for continuous task execution.',
        connectedNodes: ['langchain', 'llms'],
        projects: ['Mem-Rooted', 'Autonomous CI/CD Healing Agent'],
      },
      {
        id: 'rag',
        name: 'Retrieval-Augmented Generation (RAG)',
        maturity: 'Advanced',
        role: 'Injecting dynamic, domain-specific knowledge into LLM contexts to drastically reduce hallucinations.',
        connectedNodes: ['embeddings', 'vector-databases'],
        projects: ['Mem-Rooted', 'PAIN AWAY', 'Intelli-Credit'],
      },
      {
        id: 'embeddings',
        name: 'Embeddings & Text Representation',
        maturity: 'Advanced',
        role: 'Converting raw text into dense vector representations for mathematical similarity comparisons.',
        connectedNodes: ['vector-databases', 'rag'],
        projects: ['Mem-Rooted', 'TranslateIQ'],
      },
      {
        id: 'vector-databases',
        name: 'Vector Databases',
        maturity: 'Advanced',
        role: 'Storing and indexing high-dimensional embeddings for rapid semantic similarity search.',
        connectedNodes: ['rag', 'embeddings'],
        projects: ['Mem-Rooted', 'PAIN AWAY'],
      },
      {
        id: 'pytorch',
        name: 'PyTorch Deep Learning',
        maturity: 'Working Knowledge',
        role: 'Developing and training foundational neural network architectures and deep learning models.',
        connectedNodes: ['embeddings'],
        projects: ['TranslateIQ'],
      },
    ],
  },
  {
    id: 'backend-web',
    title: 'Backend & Web Engineering',
    subtitle: 'Robust APIs, Interactive Interfaces & System Logic',
    iconName: 'Server',
    flowSequence: 'Python/C++ Logic → FastAPI/Node.js → SQL Databases → React UI',
    description:
      'Building complete software stacks, from resilient backend data systems to interactive, user-facing web applications.',
    nodes: [
      {
        id: 'python',
        name: 'Python',
        maturity: 'Advanced',
        role: 'Primary language for AI integration, data processing, and rapid backend API development.',
        connectedNodes: ['fastapi'],
        projects: ['PAIN AWAY', 'Mem-Rooted', 'TranslateIQ', 'Intelli-Credit', 'Learnify'],
      },
      {
        id: 'cplusplus',
        name: 'C++',
        maturity: 'Working Knowledge',
        role: 'Leveraged for high-performance computing tasks, algorithmic problem solving, and strict memory management.',
        connectedNodes: [],
        projects: [],
      },
      {
        id: 'fastapi',
        name: 'FastAPI',
        maturity: 'Advanced',
        role: 'Developing high-speed, asynchronous REST APIs with automatic documentation and strict type validation.',
        connectedNodes: ['python', 'sql'],
        projects: ['PAIN AWAY', 'Mem-Rooted', 'Intelli-Credit'],
      },
      {
        id: 'nodejs',
        name: 'Node.js',
        maturity: 'Working Knowledge',
        role: 'Building scalable JavaScript-based backend services and server-side logic.',
        connectedNodes: ['javascript', 'react'],
        projects: ['Learnify'],
      },
      {
        id: 'react',
        name: 'React',
        maturity: 'Advanced',
        role: 'Engineering dynamic, component-based user interfaces for seamless web application experiences.',
        connectedNodes: ['javascript'],
        projects: ['PAIN AWAY', 'Intelli-Credit', 'Learnify'],
      },
      {
        id: 'javascript',
        name: 'JavaScript',
        maturity: 'Advanced',
        role: 'Core language powering interactive frontend behavior and full-stack web capabilities.',
        connectedNodes: ['react', 'nodejs'],
        projects: ['PAIN AWAY', 'TranslateIQ', 'Learnify'],
      },
      {
        id: 'sql',
        name: 'SQL Databases',
        maturity: 'Working Knowledge',
        role: 'Designing relational schemas, writing queries, and managing structured application data.',
        connectedNodes: ['fastapi', 'nodejs'],
        projects: ['PAIN AWAY', 'Mem-Rooted', 'Intelli-Credit'],
      },
    ],
  },
  {
    id: 'cloud-devops',
    title: 'Cloud & Infrastructure',
    subtitle: 'Containerization, Deployment & Accelerated Compute',
    iconName: 'Cloud',
    flowSequence: 'Docker Containerization → AWS ECS/Fargate → Cloud Compute',
    description:
      'Packaging applications for consistent execution and deploying them securely to scalable cloud environments.',
    nodes: [
      {
        id: 'docker',
        name: 'Docker Containerization',
        maturity: 'Working Knowledge',
        role: 'Packaging applications and their dependencies into standardized units for seamless cross-environment deployment.',
        connectedNodes: ['aws-ecs'],
        projects: ['PAIN AWAY', 'Autonomous CI/CD Healing Agent', 'Learnify'],
      },
      {
        id: 'aws-ecs',
        name: 'AWS ECS / Fargate',
        maturity: 'Working Knowledge',
        role: 'Deploying and managing containerized applications on fully managed, serverless AWS compute infrastructure.',
        connectedNodes: ['docker'],
        projects: ['PAIN AWAY', 'TranslateIQ'],
      },
      {
        id: 'aws-foundational',
        name: 'AWS (Foundational)',
        maturity: 'Working Knowledge',
        role: 'Utilizing core Amazon Web Services like EC2, S3, and RDS to support full-stack application hosting and storage.',
        connectedNodes: ['aws-ecs'],
        projects: ['PAIN AWAY', 'Intelli-Credit'],
      },
      {
        id: 'google-colab',
        name: 'Google Colab GPU',
        maturity: 'Advanced',
        role: 'Leveraging accelerated cloud GPU compute for rapid AI model prototyping, training, and execution.',
        connectedNodes: [],
        projects: ['Mem-Rooted', 'TranslateIQ'],
      },
    ],
  },
];
