import type { ExpertiseDomain } from '../types/expertise';

export const EXPERTISE_DOMAINS: ExpertiseDomain[] = [
  {
    id: 'applied-ai',
    title: 'Applied AI',
    subtitle: 'Autonomous Agent Pipelines & Hybrid Retrieval Architecture',
    iconName: 'BrainCircuit',
    flowSequence: 'LLMs → LangChain/LangGraph → RAG & Embeddings → Vector Search → Agentic Evaluation',
    description:
      'Designing production-grade cognitive pipelines where deterministic backend guardrails orchestrate stateful multi-agent reasoning, semantic vector search, and dynamic prompt routing.',
    nodes: [
      {
        id: 'llms',
        name: 'LLMs (OpenAI / Gemini / Claude)',
        maturity: 'Production',
        role: 'Core reasoning engines leveraged for structured JSON extraction, Socratic pedagogy, and multi-step diagnostic triage.',
        connectedNodes: ['prompt-engineering', 'langchain', 'langgraph', 'context-engineering'],
        projects: ['PAIN AWAY', 'Mem-Rooted', 'TranslateIQ', 'Autonomous CI/CD Healing Agent', 'Learnify'],
      },
      {
        id: 'prompt-engineering',
        name: 'Prompt Engineering & Routing',
        maturity: 'Production',
        role: 'Designing few-shot system prompts, JSON schema constraints, and deterministic intent classifiers to eliminate hallucination.',
        connectedNodes: ['context-engineering', 'rag', 'agentic-ai'],
        projects: ['PAIN AWAY', 'Mem-Rooted', 'TranslateIQ', 'Learnify'],
      },
      {
        id: 'context-engineering',
        name: 'Context Engineering & Memory Systems',
        maturity: 'Production',
        role: 'Managing long-horizon context windows using time-decay pruning curves and hierarchical graph state retrieval.',
        connectedNodes: ['rag', 'embeddings', 'vector-databases'],
        projects: ['Mem-Rooted', 'PAIN AWAY', 'Learnify'],
      },
      {
        id: 'rag',
        name: 'RAG (Retrieval-Augmented Generation)',
        maturity: 'Production',
        role: 'Injecting verified domain knowledge and clinical/financial ledgers directly into LLM context windows prior to synthesis.',
        connectedNodes: ['embeddings', 'vector-databases', 'evaluation'],
        projects: ['Mem-Rooted', 'PAIN AWAY', 'Intelli-Credit'],
      },
      {
        id: 'embeddings',
        name: 'Embeddings & Sentence Transformers',
        maturity: 'Production',
        role: 'Converting high-dimensional text strings and structured medical/financial entities into dense semantic vector representations.',
        connectedNodes: ['vector-databases', 'fine-tuning'],
        projects: ['Mem-Rooted', 'TranslateIQ'],
      },
      {
        id: 'vector-databases',
        name: 'Vector Databases & Vector Search',
        maturity: 'Production',
        role: 'Indexing millions of high-dimensional vectors with pgvector HNSW trees and hybrid Neo4j graph traversals for sub-15ms lookups.',
        connectedNodes: ['langchain', 'evaluation'],
        projects: ['Mem-Rooted', 'PAIN AWAY'],
      },
      {
        id: 'langchain',
        name: 'LangChain & Tool Orchestration',
        maturity: 'Production',
        role: 'Orchestrating agent chains, structured tool-calling wrappers, and database schema parsers for autonomous execution.',
        connectedNodes: ['langgraph', 'agentic-ai', 'multi-agent-systems'],
        projects: ['Mem-Rooted', 'Autonomous CI/CD Healing Agent'],
      },
      {
        id: 'langgraph',
        name: 'LangGraph Stateful Workflows',
        maturity: 'Advanced',
        role: 'Building cyclic, stateful multi-agent graphs with persistent check-pointing and conditional edge transitions.',
        connectedNodes: ['agentic-ai', 'multi-agent-systems'],
        projects: ['Mem-Rooted', 'Autonomous CI/CD Healing Agent'],
      },
      {
        id: 'agentic-ai',
        name: 'Agentic AI & Self-Healing Loops',
        maturity: 'Production',
        role: 'Engineering autonomous agents that execute compiler AST parsers, run Docker test sandboxes, and self-patch code syntax.',
        connectedNodes: ['multi-agent-systems', 'evaluation'],
        projects: ['Autonomous CI/CD Healing Agent', 'Mem-Rooted'],
      },
      {
        id: 'multi-agent-systems',
        name: 'Multi-Agent Systems',
        maturity: 'Advanced',
        role: 'Coordinating specialized subagent swarms (e.g., Researcher, Codebase Inspector, Security Auditor) via structured message passing.',
        connectedNodes: ['evaluation'],
        projects: ['Autonomous CI/CD Healing Agent', 'Mem-Rooted'],
      },
      {
        id: 'fine-tuning',
        name: 'Fine Tuning & Domain Adaptation',
        maturity: 'Advanced',
        role: 'Adapting smaller open weights and specialized neural translation models to strict enterprise domain glossaries.',
        connectedNodes: ['evaluation'],
        projects: ['TranslateIQ'],
      },
      {
        id: 'evaluation',
        name: 'Evaluation & Telemetry (LangSmith)',
        maturity: 'Production',
        role: 'Automating continuous accuracy benchmarks, regression matrices, and latency tracing across agentic generation pipelines.',
        connectedNodes: ['llms'],
        projects: ['Mem-Rooted', 'PAIN AWAY', 'TranslateIQ'],
      },
    ],
  },
  {
    id: 'backend-engineering',
    title: 'Backend Engineering',
    subtitle: 'High-Concurrency Event-Driven & REST/WebSocket Microservices',
    iconName: 'Server',
    flowSequence: 'API Architecture → FastAPI/Python → Authentication/JWT → SQLAlchemy/Alembic → PostgreSQL & Async Caching',
    description:
      'Architecting resilient, self-documenting server engines with strict Pydantic type validation, asynchronous event loops, and transactional database integrity.',
    nodes: [
      {
        id: 'api-architecture',
        name: 'API Architecture & Design Contracts',
        maturity: 'Production',
        role: 'Freezing self-documenting REST and WebSocket schema boundaries via OpenAPI/JSONSchema before application code begins.',
        connectedNodes: ['fastapi', 'python', 'rest-apis'],
        projects: ['PAIN AWAY', 'Mem-Rooted', 'TranslateIQ', 'Intelli-Credit', 'Learnify'],
      },
      {
        id: 'fastapi',
        name: 'FastAPI & Starlette Hubs',
        maturity: 'Production',
        role: 'High-speed asynchronous Python API framework providing native concurrency, automatic Pydantic v2 serialization, and live WebSockets.',
        connectedNodes: ['python', 'rest-apis', 'async-processing'],
        projects: ['PAIN AWAY', 'Mem-Rooted', 'Intelli-Credit', 'Autonomous CI/CD Healing Agent'],
      },
      {
        id: 'python',
        name: 'Python 3.12+ Core & Typing',
        maturity: 'Production',
        role: 'Enforcing strict type hints, structural pattern matching, and zero-overhead async coroutines across core domain services.',
        connectedNodes: ['sqlalchemy', 'async-processing', 'background-jobs'],
        projects: ['PAIN AWAY', 'Mem-Rooted', 'TranslateIQ', 'Intelli-Credit', 'Autonomous CI/CD Healing Agent', 'Learnify'],
      },
      {
        id: 'rest-apis',
        name: 'REST APIs & WebSockets',
        maturity: 'Production',
        role: 'Delivering sub-15ms bidirectional state broadcasts across multi-tenant clinic reception terminals and live code sandboxes.',
        connectedNodes: ['authentication', 'jwt'],
        projects: ['PAIN AWAY', 'Learnify', 'Intelli-Credit'],
      },
      {
        id: 'authentication',
        name: 'Authentication & HIPAA RBAC',
        maturity: 'Production',
        role: 'Enforcing fine-grained Role-Based Access Control dividing medical triage access from administrative financial audit ledgers.',
        connectedNodes: ['jwt', 'postgresql'],
        projects: ['PAIN AWAY', 'Intelli-Credit'],
      },
      {
        id: 'jwt',
        name: 'JWT & Stateless Session Security',
        maturity: 'Production',
        role: 'Signing cryptographically verifiable access/refresh tokens with short expiration windows and Redis blacklist revocation checks.',
        connectedNodes: ['postgresql', 'caching'],
        projects: ['PAIN AWAY', 'Learnify'],
      },
      {
        id: 'sqlalchemy',
        name: 'SQLAlchemy v2 ORM Core',
        maturity: 'Production',
        role: 'Mapping complex domain entities with async session management, explicit transaction boundaries, and raw SQL optimization.',
        connectedNodes: ['alembic', 'postgresql'],
        projects: ['PAIN AWAY', 'Mem-Rooted', 'Intelli-Credit'],
      },
      {
        id: 'alembic',
        name: 'Alembic Database Migrations',
        maturity: 'Production',
        role: 'Managing deterministic, version-controlled schema transformations tested against CI staging containers prior to release.',
        connectedNodes: ['postgresql'],
        projects: ['PAIN AWAY', 'Mem-Rooted', 'TranslateIQ'],
      },
      {
        id: 'postgresql',
        name: 'PostgreSQL ACID & RLS Core',
        maturity: 'Production',
        role: 'Ensuring zero data loss (`RPO=0`) and enforcing multi-tenant schema isolation via native Row-Level Security guardrails.',
        connectedNodes: ['caching', 'async-processing'],
        projects: ['PAIN AWAY', 'Mem-Rooted', 'TranslateIQ', 'Intelli-Credit', 'Learnify'],
      },
      {
        id: 'caching',
        name: 'Redis Distributed Caching & Pub/Sub',
        maturity: 'Production',
        role: 'Decoupling WebSocket broadcast state across horizontal API nodes and caching high-frequency triage indexes for sub-5ms reads.',
        connectedNodes: ['async-processing', 'background-jobs'],
        projects: ['PAIN AWAY', 'Mem-Rooted', 'Learnify'],
      },
      {
        id: 'async-processing',
        name: 'Async Processing & Coroutines',
        maturity: 'Production',
        role: 'Orchestrating non-blocking I/O routines across database queries, external AI model inference calls, and webhook ingestions.',
        connectedNodes: ['background-jobs'],
        projects: ['PAIN AWAY', 'Mem-Rooted', 'TranslateIQ', 'Autonomous CI/CD Healing Agent'],
      },
      {
        id: 'background-jobs',
        name: 'Background Jobs & Celery / RabbitMQ',
        maturity: 'Production',
        role: 'Offloading CPU-heavy tasks like AST code translation, SMS patient reminders, and SHAP attribution to durable worker queues.',
        connectedNodes: ['api-architecture'],
        projects: ['PAIN AWAY', 'TranslateIQ', 'Intelli-Credit', 'Mem-Rooted'],
      },
    ],
  },
  {
    id: 'frontend-engineering',
    title: 'Frontend Engineering',
    subtitle: 'Strict Type-Safe React 19 Component Systems & UI Ergonomics',
    iconName: 'Layout',
    flowSequence: 'TypeScript & React 19 → Component Systems → Tailwind CSS → Framer Motion → Performance & Accessibility',
    description:
      'Engineering high-frequency user interfaces with zero-latency concurrent state updates, design token systems, and strict keyboard accessible ergonomics.',
    nodes: [
      {
        id: 'react',
        name: 'React 19 & Concurrent Mode',
        maturity: 'Production',
        role: 'Leveraging concurrent transitions and server/client action boundaries to maintain 60FPS UI rendering during high-volume data streams.',
        connectedNodes: ['typescript', 'component-systems', 'state-management'],
        projects: ['PAIN AWAY', 'Intelli-Credit', 'Learnify'],
      },
      {
        id: 'typescript',
        name: 'Strict TypeScript (`verbatimModuleSyntax`)',
        maturity: 'Production',
        role: 'Enforcing zero runtime type mismatches, explicit `import type` boundaries, and end-to-end type safety with backend API definitions.',
        connectedNodes: ['component-systems', 'state-management'],
        projects: ['PAIN AWAY', 'TranslateIQ', 'Intelli-Credit', 'Learnify'],
      },
      {
        id: 'component-systems',
        name: 'Compound Component Systems',
        maturity: 'Production',
        role: 'Architecting reusable, highly extensible primitive modules (`Card`, `Badge`, `Button`, `Dialog`) with clean polymorphism.',
        connectedNodes: ['tailwindcss', 'framer-motion'],
        projects: ['PAIN AWAY', 'Learnify'],
      },
      {
        id: 'tailwindcss',
        name: 'Vanilla & Tailwind CSS Design System',
        maturity: 'Production',
        role: 'Defining curated HSL color tokens, dark mode overlays, and responsive spacing grids without ad-hoc utility clutter.',
        connectedNodes: ['responsive-design', 'accessibility'],
        projects: ['PAIN AWAY', 'Learnify'],
      },
      {
        id: 'framer-motion',
        name: 'Framer Motion & Micro-Animations',
        maturity: 'Production',
        role: 'Orchestrating subtle layout animations (`layoutId`), staggered list reveals, and hardware-accelerated spring transitions.',
        connectedNodes: ['performance-optimization'],
        projects: ['PAIN AWAY', 'Learnify'],
      },
      {
        id: 'state-management',
        name: 'State Management & Concurrent Store',
        maturity: 'Production',
        role: 'Synchronizing local UI state with live WebSocket updates using optimistic UI patterns and zero unnecessary re-renders.',
        connectedNodes: ['performance-optimization'],
        projects: ['PAIN AWAY', 'Learnify'],
      },
      {
        id: 'responsive-design',
        name: 'Responsive Design & Multi-Device Topologies',
        maturity: 'Production',
        role: 'Adapting dense triage queues and clinical charts fluidly across 4K desktop terminals, tablets, and mobile devices.',
        connectedNodes: ['accessibility'],
        projects: ['PAIN AWAY', 'Learnify'],
      },
      {
        id: 'accessibility',
        name: 'Accessibility (ARIA & Keyboard Ergonomics)',
        maturity: 'Production',
        role: 'Enforcing semantic HTML5 markup, high-contrast ratios, and rapid keyboard shortcut traversal for clinical reception operators.',
        connectedNodes: ['performance-optimization'],
        projects: ['PAIN AWAY', 'Learnify'],
      },
      {
        id: 'performance-optimization',
        name: 'Performance Optimization & Code Splitting',
        maturity: 'Production',
        role: 'Achieving sub-1 second bundle loading, dynamic route code splitting, and memory leak prevention in long-running dashboards.',
        connectedNodes: ['react'],
        projects: ['PAIN AWAY', 'Learnify'],
      },
    ],
  },
  {
    id: 'data-engineering',
    title: 'Data Engineering',
    subtitle: 'High-Throughput Financial Extraction & Mathematical Pipelines',
    iconName: 'Database',
    flowSequence: 'Ingestion & Cleaning → Pandas/NumPy → Feature Engineering → Scikit-Learn/XGBoost → Analytics & Visualization',
    description:
      'Building immutable tabular data extraction lines, real-time feature transformations, and explainable statistical risk matrices for enterprise underwriting.',
    nodes: [
      {
        id: 'data-pipelines',
        name: 'Data Pipelines & Ingestion',
        maturity: 'Production',
        role: 'Extracting unstructured financial statements, tax returns, and clinical metrics via OCR and streaming webhook receivers.',
        connectedNodes: ['cleaning', 'pandas'],
        projects: ['Intelli-Credit', 'PAIN AWAY'],
      },
      {
        id: 'cleaning',
        name: 'Data Cleaning & Validation Matrices',
        maturity: 'Production',
        role: 'Detecting missing balance sheet entries, normalizing currency scales, and filtering statistical outliers before modeling.',
        connectedNodes: ['pandas', 'numpy'],
        projects: ['Intelli-Credit'],
      },
      {
        id: 'pandas',
        name: 'Pandas & Tabular Transformations',
        maturity: 'Production',
        role: 'Executing vectorized operations across multi-year commercial lending ledgers and inventory reconciliation logs.',
        connectedNodes: ['numpy', 'feature-engineering'],
        projects: ['Intelli-Credit', 'PAIN AWAY'],
      },
      {
        id: 'numpy',
        name: 'NumPy Mathematical Core',
        maturity: 'Production',
        role: 'Powering high-speed linear algebra calculations, distance metrics, and vector calculations for similarity matching.',
        connectedNodes: ['feature-engineering', 'scikit-learn'],
        projects: ['Intelli-Credit', 'Mem-Rooted'],
      },
      {
        id: 'feature-engineering',
        name: 'Feature Engineering & Ratio Synthesis',
        maturity: 'Production',
        role: 'Constructing predictive commercial credit ratios (DSCR, Debt-to-Equity, Working Capital Turnover) from raw ledger entries.',
        connectedNodes: ['scikit-learn'],
        projects: ['Intelli-Credit'],
      },
      {
        id: 'scikit-learn',
        name: 'Scikit-Learn & Statistical Modeling',
        maturity: 'Production',
        role: 'Running baseline classification guardrails, anomaly detection models, and data cross-validation splits.',
        connectedNodes: ['analytics', 'visualization'],
        projects: ['Intelli-Credit', 'Learnify'],
      },
      {
        id: 'analytics',
        name: 'Director Financial & Clinical Analytics',
        maturity: 'Production',
        role: 'Aggregating daily billing realization rates and physician throughput directly from live operational database ledgers.',
        connectedNodes: ['visualization'],
        projects: ['PAIN AWAY', 'Intelli-Credit'],
      },
      {
        id: 'visualization',
        name: 'Interactive Visualization & SHAP Audit Charts',
        maturity: 'Production',
        role: 'Rendering clear attribution charts explaining exact positive/negative risk impacts for commercial loan underwriters.',
        connectedNodes: ['data-pipelines'],
        projects: ['Intelli-Credit', 'PAIN AWAY'],
      },
    ],
  },
  {
    id: 'cloud-infrastructure',
    title: 'Cloud & Infrastructure',
    subtitle: 'Containerized Multi-AZ Deployment & CI/CD Automation',
    iconName: 'Cloud',
    flowSequence: 'Docker Containerization → CI/CD Pipelines → AWS Foundational / Google Cloud → Cloud Storage & Security → Monitoring',
    description:
      'Provisioning deterministic, zero-downtime production environments with strict container sandboxing, automated secrets management, and real-time observability.',
    nodes: [
      {
        id: 'docker',
        name: 'Docker & Containerization SDK',
        maturity: 'Production',
        role: 'Packaging microservices into reproducible images and orchestrating ephemeral, CPU/memory-restricted execution sandboxes for untrusted code.',
        connectedNodes: ['containerization', 'ci-cd'],
        projects: ['PAIN AWAY', 'Autonomous CI/CD Healing Agent', 'Learnify', 'TranslateIQ'],
      },
      {
        id: 'containerization',
        name: 'Containerization & Multi-Tenant Enclaves',
        maturity: 'Production',
        role: 'Isolating tenant runtimes and executing ephemeral compilation checks (`128MB` RAM limits) safely.',
        connectedNodes: ['ci-cd', 'deployment'],
        projects: ['Autonomous CI/CD Healing Agent', 'Learnify', 'PAIN AWAY'],
      },
      {
        id: 'ci-cd',
        name: 'CI/CD Automation & GitHub Actions',
        maturity: 'Production',
        role: 'Automating multi-stage linting, unit/integration testing, database migration verification, and zero-downtime container rollouts.',
        connectedNodes: ['deployment', 'aws'],
        projects: ['PAIN AWAY', 'Autonomous CI/CD Healing Agent', 'TranslateIQ'],
      },
      {
        id: 'deployment',
        name: 'Zero-Downtime Deployment & Reverse Proxy',
        maturity: 'Production',
        role: 'Orchestrating Nginx reverse proxies, SSL/TLS termination, and blue-green deployment switches without dropping WebSocket connections.',
        connectedNodes: ['aws', 'google-cloud'],
        projects: ['PAIN AWAY', 'TranslateIQ'],
      },
      {
        id: 'aws',
        name: 'AWS (Foundational ECS / RDS / S3 / ElastiCache)',
        maturity: 'Production',
        role: 'Deploying Multi-AZ PostgreSQL clusters, containerized ECS Fargate services, and Redis caching layers for high-availability production systems.',
        connectedNodes: ['google-cloud', 'cloud-storage'],
        projects: ['PAIN AWAY', 'TranslateIQ', 'Intelli-Credit'],
      },
      {
        id: 'google-cloud',
        name: 'Google Cloud Platform & Vertex AI',
        maturity: 'Advanced',
        role: 'Leveraging foundational Google Cloud storage endpoints and managed Vertex AI model routing pipelines.',
        connectedNodes: ['cloud-storage', 'security'],
        projects: ['Mem-Rooted', 'TranslateIQ'],
      },
      {
        id: 'cloud-storage',
        name: 'Cloud Storage & Immutable Vaults',
        maturity: 'Production',
        role: 'Storing encrypted financial ledgers, tax balance sheets, and localized UI asset bundles across S3 and CloudFront CDNs.',
        connectedNodes: ['security', 'monitoring'],
        projects: ['Intelli-Credit', 'TranslateIQ'],
      },
      {
        id: 'security',
        name: 'Security, Secrets Management & Enclaves',
        maturity: 'Production',
        role: 'Enforcing strict environment variable vaults, Row-Level Security guardrails, and cryptographic hashing across all data tiers.',
        connectedNodes: ['monitoring'],
        projects: ['PAIN AWAY', 'Intelli-Credit'],
      },
      {
        id: 'monitoring',
        name: 'Monitoring, Observability & Telemetry',
        maturity: 'Production',
        role: 'Tracking system CPU/memory saturation, API latency histograms, and WebSocket drop rates via Prometheus and Grafana dashboards.',
        connectedNodes: ['docker'],
        projects: ['PAIN AWAY', 'Mem-Rooted', 'Autonomous CI/CD Healing Agent'],
      },
    ],
  },
  {
    id: 'software-architecture',
    title: 'Software Architecture',
    subtitle: 'System Topology, Microservices & Domain-Driven Production Rigor',
    iconName: 'Layers',
    flowSequence: 'Engineering Planning → Business Workflows → System Design → Modular Microservices → Scalable APIs & Database Design',
    description:
      'Translating complex business bottlenecks into structured domain models, decoupled event queues, and deterministic finite state machines prior to writing code.',
    nodes: [
      {
        id: 'system-design',
        name: 'System Design & High-Concurrency Topologies',
        maturity: 'Production',
        role: 'Designing 5-tier architectures capable of scaling horizontally under 10x traffic surges while guaranteeing zero data race anomalies.',
        connectedNodes: ['microservices', 'modular-design'],
        projects: ['PAIN AWAY', 'Mem-Rooted', 'TranslateIQ', 'Intelli-Credit'],
      },
      {
        id: 'microservices',
        name: 'Event-Driven Microservices Architecture',
        maturity: 'Production',
        role: 'Decoupling synchronous API gateways from background Celery/RabbitMQ workers to maintain UI responsiveness during heavy processing.',
        connectedNodes: ['modular-design', 'scalable-apis'],
        projects: ['PAIN AWAY', 'TranslateIQ', 'Autonomous CI/CD Healing Agent'],
      },
      {
        id: 'modular-design',
        name: 'Strict Modular Design & Domain Isolation',
        maturity: 'Production',
        role: 'Isolating domain boundaries so modifications to clinical inventory ledgers never risk breaking reception scheduling workflows.',
        connectedNodes: ['scalable-apis', 'business-workflows'],
        projects: ['PAIN AWAY', 'Mem-Rooted'],
      },
      {
        id: 'scalable-apis',
        name: 'Scalable API & Event Contracts',
        maturity: 'Production',
        role: 'Establishing versioned, strongly typed REST and GraphQL interfaces that decouple frontend consumers from underlying database migrations.',
        connectedNodes: ['business-workflows', 'database-design'],
        projects: ['PAIN AWAY', 'TranslateIQ', 'Intelli-Credit'],
      },
      {
        id: 'business-workflows',
        name: 'Business Workflows & State Machines',
        maturity: 'Production',
        role: 'Codifying real-world operational steps (Scheduled → Checked-In → Triage → Consultation → Billing) into server-verified finite state machines.',
        connectedNodes: ['database-design', 'engineering-planning'],
        projects: ['PAIN AWAY', 'Intelli-Credit', 'Learnify'],
      },
      {
        id: 'database-design',
        name: 'Database Design & Normalized Schemas',
        maturity: 'Production',
        role: 'Modeling normalized relational structures (`3NF`), JSONB document extensions, and trigram indexing trees (`pg_trgm`) for sub-millisecond search.',
        connectedNodes: ['engineering-planning', 'production-architecture'],
        projects: ['PAIN AWAY', 'Mem-Rooted', 'Intelli-Credit'],
      },
      {
        id: 'engineering-planning',
        name: 'Engineering Planning & Capability Matrix',
        maturity: 'Production',
        role: 'Deconstructing massive architecture RFCs into sequential, zero-risk milestone deliverables before any code development commences.',
        connectedNodes: ['production-architecture'],
        projects: ['PAIN AWAY', 'Autonomous CI/CD Healing Agent'],
      },
      {
        id: 'production-architecture',
        name: 'Production Architecture & Reliability Mindset',
        maturity: 'Production',
        role: 'Treating staging environments as live production instances by enforcing rigorous error boundary recovery and automated regression matrices.',
        connectedNodes: ['system-design'],
        projects: ['PAIN AWAY', 'Mem-Rooted', 'TranslateIQ', 'Intelli-Credit', 'Autonomous CI/CD Healing Agent', 'Learnify'],
      },
    ],
  },
  {
    id: 'engineering-tools',
    title: 'Engineering Tools & DevOps',
    subtitle: 'Daily Consulting Rigor & Automated CI/CD Tooling',
    iconName: 'Wrench',
    flowSequence: 'Git / GitHub → VS Code & Linux Terminal → Postman / Jupyter → Figma → GitHub Actions Automation',
    description:
      'Mastering daily engineering instruments for rapid code inspection, API verification, interactive data exploration, and automated delivery pipelines.',
    nodes: [
      {
        id: 'git',
        name: 'Git Version Control & Branching Strategies',
        maturity: 'Production',
        role: 'Enforcing atomic commits, interactive rebases (`git rebase -i`), structured pull requests, and semantic branch hierarchies.',
        connectedNodes: ['github', 'vs-code'],
        projects: ['PAIN AWAY', 'Mem-Rooted', 'TranslateIQ', 'Intelli-Credit', 'Autonomous CI/CD Healing Agent', 'Learnify'],
      },
      {
        id: 'github',
        name: 'GitHub Repository & Code Review Ecosystem',
        maturity: 'Production',
        role: 'Orchestrating automated PR checks, branch protection guardrails, code review approvals, and release versioning.',
        connectedNodes: ['github-actions', 'vs-code'],
        projects: ['PAIN AWAY', 'Autonomous CI/CD Healing Agent'],
      },
      {
        id: 'vs-code',
        name: 'VS Code & Advanced IDE Workflows',
        maturity: 'Production',
        role: 'Leveraging strict TypeScript language servers (`tsserver`), integrated debuggers, and AST inspection tools for high-velocity coding.',
        connectedNodes: ['linux', 'postman'],
        projects: ['PAIN AWAY', 'Mem-Rooted', 'TranslateIQ', 'Intelli-Credit', 'Autonomous CI/CD Healing Agent', 'Learnify'],
      },
      {
        id: 'linux',
        name: 'Linux System Administration & Shell Scripting',
        maturity: 'Production',
        role: 'Navigating production servers via SSH, configuring Nginx daemons, managing systemd daemons, and writing deterministic bash pipelines.',
        connectedNodes: ['github-actions', 'postman'],
        projects: ['PAIN AWAY', 'Autonomous CI/CD Healing Agent', 'TranslateIQ'],
      },
      {
        id: 'postman',
        name: 'Postman & API Contract Verification Suite',
        maturity: 'Production',
        role: 'Automating endpoint regression suites, simulating multi-tenant JWT headers, and benchmarking WebSocket throughput before frontend integration.',
        connectedNodes: ['jupyter', 'figma'],
        projects: ['PAIN AWAY', 'Intelli-Credit', 'TranslateIQ'],
      },
      {
        id: 'jupyter',
        name: 'Jupyter Notebooks & Exploratory Data Analysis',
        maturity: 'Production',
        role: 'Prototyping vector embedding algorithms, inspecting OCR balance sheet distributions, and calculating SHAP value charts interactively.',
        connectedNodes: ['figma', 'github-actions'],
        projects: ['Intelli-Credit', 'Mem-Rooted'],
      },
      {
        id: 'figma',
        name: 'Figma Design System Inspection & Prototyping',
        maturity: 'Production',
        role: 'Inspecting exact spacing hierarchies, extracting HSL color tokens, and validating interactive prototype flows prior to UI engineering.',
        connectedNodes: ['github-actions'],
        projects: ['PAIN AWAY', 'Learnify'],
      },
      {
        id: 'github-actions',
        name: 'GitHub Actions Automated CI/CD Pipelines',
        maturity: 'Production',
        role: 'Writing declarative YAML workflows that trigger automated Docker build verifications and AST self-healing loops upon every git push.',
        connectedNodes: ['git'],
        projects: ['PAIN AWAY', 'Autonomous CI/CD Healing Agent', 'TranslateIQ'],
      },
    ],
  },
];
